services:
  app:
    container_name: ${DOCKER_PROJECT_NAME}
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysqldb
    links:
      - mysqldb
      - redis
    networks:
      - earn_expense_network
  mysqldb:
    image: mysql:8.0
    container_name: ${DOCKER_PROJECT_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    networks:
      - earn_expense_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${DOCKER_PROJECT_NAME}_phpmyadmin
    restart: always
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 8080:8080
    networks:
      - earn_expense_network

  redis:
    container_name: ${DOCKER_PROJECT_NAME}_redis_cache
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_cache:/data
volumes:
  redis_cache:
networks:
  earn_expense_network:
